Repository gbowne1/TwitchBot, pull requests merged in 2024-03, with the labels that each got.

#77 49 bug react app fails to retain user color scheme preference across routes
  src/client/src/App.js
  src/client/src/__tests__/AppBar.test.js
  src/client/src/__tests__/themeContext.test.js
  src/client/src/components/AppBar.js
  src/client/src/components/Settings.js
  src/client/src/context/themeContext.js
Labels: enhancement

#80 Resolve Deprecation warnings in Github Actions
  .github/workflows/code-quality-checks.yml
Labels: bug

#82 61 testing add tests for Login, Register, Logout
  src/client/src/__tests__/Login.test.js
  src/client/src/components/Login.css
  src/client/src/components/Login.js
  src/client/src/pages/HomePage.css
  src/client/src/pages/HomePage.js
  src/server/.eslintrc.cjs
  src/server/__tests__/server.test.js
  src/server/package-lock.json
  src/server/package.json
  src/server/server.js
Labels: testing

#83 making some minor improvements to the contexts
  src/client/src/components/DrawerMenu.js
  src/client/src/components/LeaderBoard.js
  src/client/src/components/ProtectedRoute.js
  src/client/src/context/authContext.js
  src/client/src/context/themeContext.js
Labels: enhancement

#84 Resolve cross origin login errors between server and client (#72)
  src/client/src/context/authContext.js
  src/server/.env-example
  src/server/server.js
Labels: bug

#85 Reference theme color via hook
  src/client/src/components/DrawerMenu.js
Labels: bug
