Repository gbowne1/TwitchBot, pull requests merged in 2024-02, with the labels that each got.

#12 [Fixed] Settings page not working #9
  src/client/package-lock.json
  src/client/src/components/Settings.js
Labels: bug, help wanted

#21 Fix webpack/babel notice
  src/client/package-lock.json
  src/client/package.json
Labels: bug, enhancement, help wanted

#20 Add Dark Mode Toggle
  src/client/src/App.js
  src/client/src/ThemeProvider.js
  src/client/src/components/AppBar.js
  src/client/src/components/Settings.js
Labels: bug, enhancement, help wanted, good first issue

#30 fix bug #25: TypeError - colorMode undefined
  src/client/src/App.js
Labels: bug, help wanted, good first issue

#37 Updated ReadMe and Contribution files
  CONTRIBUTING.md
  README.md
Labels: documentation

#34 tests added for About.js and AppBar.js
  src/client/package.json
  src/client/src/App.js
  src/client/src/App.test.js
  src/client/src/__tests__/About.test.js
  src/client/src/__tests__/AppBar.test.js
  src/client/src/components/AppBar.js
  src/client/src/components/Settings.js
  src/client/src/setupTests.js
Labels: enhancement, help wanted, good first issue

#39 add dark mode / light mode drawer link style
  src/client/src/components/DrawerMenu.js
Labels: bug

#44 adding login and logout functionalities
  src/client/package-lock.json
  src/client/package.json
  src/client/src/App.js
  src/client/src/context/authContext.js
  src/client/src/index.js
  src/client/src/pages/HomePage.css
  src/client/src/pages/HomePage.js
  src/client/src/routes.js
  src/server/db/db.js
  src/server/package-lock.json
  src/server/package.json
  src/server/server.js
Labels: enhancement, help wanted, good first issue

#47 adding eye to show/hide password in the field
  src/client/package-lock.json
  src/client/src/pages/HomePage.css
  src/client/src/pages/HomePage.js
Labels: enhancement, help wanted

#51 CommandUsage and dynamic params tested
  src/client/src/__tests__/CommandUsage.test.js
  src/client/src/components/CommandUsage.js
Labels: testing

#53 add routes protection
  src/client/src/components/DrawerMenu.js
  src/client/src/components/ProtectedRoute.js
  src/client/src/routes.js
Labels: enhancement

#56 tests done for Help.js
  src/client/src/__tests__/About.test.js
  src/client/src/__tests__/Help.test.js
  src/client/src/components/About.js
  src/client/src/components/Help.js
Labels: testing

#62 32 todo bug clicking on any of the commands doesnt do anything yet
  src/client/package.json
  src/client/src/__tests__/CommandCard.test.js
  src/client/src/__tests__/CommandList.test.js
  src/client/src/__tests__/allCommands.test.js
  src/client/src/commands/allCommands.js
  src/client/src/components/CommandCard.css
  src/client/src/components/CommandCard.js
  src/client/src/components/CommandList.css
  src/client/src/components/CommandList.js
Labels: bug, enhancement, testing

#60 fix log in bug
  src/server/server.js
Labels: bug

#63 Add linting and formatting configuration
  src/client/.editorconfig
  src/client/.eslintrc.cjs
  src/client/.prettierrc
  src/client/package-lock.json
  src/client/package.json
  src/client/public/index.html
  src/client/quick-lint-js.config
  src/client/src/App.css
  src/client/src/App.js
  src/client/src/ThemeProvider.js
  src/client/src/__tests__/AppBar.test.js
  src/client/src/__tests__/CommandCard.test.js
  src/client/src/__tests__/CommandList.test.js
  src/client/src/__tests__/allCommands.test.js
  src/client/src/components/About.js
  src/client/src/components/CommandCard.js
  src/client/src/components/CommandList.css
  src/client/src/components/CommandList.js
  src/client/src/components/CommandUsage.js
  src/client/src/components/DrawerMenu.js
  src/client/src/components/Help.js
  src/client/src/components/Home.js
  src/client/src/components/LeaderBoard.js
  src/client/src/components/ProtectedRoute.js
  src/client/src/components/Settings.js
  src/client/src/components/TemplateComponent.js
  src/client/src/context/authContext.js
  src/client/src/index.css
  src/client/src/index.js
  src/client/src/pages/AboutPage.js
  src/client/src/pages/CommandListPage.js
  src/client/src/pages/CommandUsagePage.js
  src/client/src/pages/HelpPage.js
  src/client/src/pages/HomePage.js
  src/client/src/pages/LeaderBoardPage.js
  src/client/src/pages/SettingsPage.js
  src/client/src/pages/index.js
  src/client/src/registerServiceWorker.js
  src/client/src/reportWebVitals.js
  src/client/src/routes.js
  src/client/src/serviceWorker.js
  src/server/.editorconfig
  src/server/.eslintrc.cjs
  src/server/.prettierrc
  src/server/app.js
  src/server/package-lock.json
  src/server/package.json
  src/server/quick-lint-js.config
  src/server/server.js
Labels: enhancement

#68 64 lint format documentation / automated code quality checks
  .github/workflows/code-quality-checks.yml
  src/client/README.md
  src/server/README.md
  src/server/commands/accountage.js
  src/server/commands/ban.js
  src/server/commands/discord.js
  src/server/commands/famousCommand.js
  src/server/commands/followage.js
  src/server/commands/lurk.js
  src/server/commands/timeout.js
  src/server/commands/uptime.js
  src/server/package.json
Labels: documentation, enhancement, testing

#74 rename container test for about page
  src/client/src/__tests__/About.test.js
Labels: testing
